-- MySQL Script generated by MySQL Workbench
-- sex 01 nov 2019 07:57:08 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_good_acai
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_good_acai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_good_acai` DEFAULT CHARACTER SET utf8 ;
USE `db_good_acai` ;

-- -----------------------------------------------------
-- Table `db_good_acai`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_good_acai`.`perfil` (
  `id` MEDIUMTEXT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_good_acai`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_good_acai`.`usuario` (
  `id` MEDIUMTEXT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `id_perfil` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_perfil_idx` (`id_perfil` ASC),
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `db_good_acai`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
